#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Caimomo.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CaiMoMo_TC")]
	public partial class EasyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSysGroupUser(SysGroupUser instance);
    partial void UpdateSysGroupUser(SysGroupUser instance);
    partial void DeleteSysGroupUser(SysGroupUser instance);
    partial void InsertBaseUserRight(BaseUserRight instance);
    partial void UpdateBaseUserRight(BaseUserRight instance);
    partial void DeleteBaseUserRight(BaseUserRight instance);
    partial void InsertBaseSystemConfig(BaseSystemConfig instance);
    partial void UpdateBaseSystemConfig(BaseSystemConfig instance);
    partial void DeleteBaseSystemConfig(BaseSystemConfig instance);
    partial void InsertBaseSystemConfigDefault(BaseSystemConfigDefault instance);
    partial void UpdateBaseSystemConfigDefault(BaseSystemConfigDefault instance);
    partial void DeleteBaseSystemConfigDefault(BaseSystemConfigDefault instance);
    #endregion
		
		public EasyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CaiMoMo_TCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EasyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EasyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EasyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EasyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SysGroupUser> SysGroupUser
		{
			get
			{
				return this.GetTable<SysGroupUser>();
			}
		}
		
		public System.Data.Linq.Table<BaseUserRight> BaseUserRight
		{
			get
			{
				return this.GetTable<BaseUserRight>();
			}
		}
		
		public System.Data.Linq.Table<BaseSystemConfig> BaseSystemConfig
		{
			get
			{
				return this.GetTable<BaseSystemConfig>();
			}
		}
		
		public System.Data.Linq.Table<BaseSystemConfigDefault> BaseSystemConfigDefault
		{
			get
			{
				return this.GetTable<BaseSystemConfigDefault>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SysGroupUser")]
	public partial class SysGroupUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UID;
		
		private int _GroupID;
		
		private int _StoreID;
		
		private string _UserID;
		
		private string _TrueName;
		
		private string _Password;
		
		private string _CurrentToken;
		
		private System.Nullable<bool> _AllStore;
		
		private string _StoreList;
		
		private string _MACBind;
		
		private string _Telephone;
		
		private string _QQ;
		
		private string _WXID;
		
		private string _ShouQuanCode;
		
		private System.Nullable<int> _CheckCode;
		
		private System.Nullable<System.DateTime> _LastCheckTime;
		
		private System.Nullable<bool> _IsManager;
		
		private System.Nullable<bool> _IsEnable;
		
		private System.Nullable<decimal> _YouMian;
		
		private string _PasswordBak;
		
		private System.Nullable<System.DateTime> _AddTime;
		
		private string _AddUser;
		
		private System.Nullable<System.DateTime> _UpdateTime;
		
		private string _UpdateUser;
		
		private string _OtherAccountType;
		
		private string _OtherUserName;
		
		private string _OtherPassWord;
		
		private System.Nullable<bool> _IsGuestManager;
		
		private System.Nullable<int> _YouMianBiLi;
		
		private System.Nullable<int> _ZheKouBiLi;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUIDChanging(string value);
    partial void OnUIDChanged();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnStoreIDChanging(int value);
    partial void OnStoreIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnTrueNameChanging(string value);
    partial void OnTrueNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCurrentTokenChanging(string value);
    partial void OnCurrentTokenChanged();
    partial void OnAllStoreChanging(System.Nullable<bool> value);
    partial void OnAllStoreChanged();
    partial void OnStoreListChanging(string value);
    partial void OnStoreListChanged();
    partial void OnMACBindChanging(string value);
    partial void OnMACBindChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnQQChanging(string value);
    partial void OnQQChanged();
    partial void OnWXIDChanging(string value);
    partial void OnWXIDChanged();
    partial void OnShouQuanCodeChanging(string value);
    partial void OnShouQuanCodeChanged();
    partial void OnCheckCodeChanging(System.Nullable<int> value);
    partial void OnCheckCodeChanged();
    partial void OnLastCheckTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCheckTimeChanged();
    partial void OnIsManagerChanging(System.Nullable<bool> value);
    partial void OnIsManagerChanged();
    partial void OnIsEnableChanging(System.Nullable<bool> value);
    partial void OnIsEnableChanged();
    partial void OnYouMianChanging(System.Nullable<decimal> value);
    partial void OnYouMianChanged();
    partial void OnPasswordBakChanging(string value);
    partial void OnPasswordBakChanged();
    partial void OnAddTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnAddTimeChanged();
    partial void OnAddUserChanging(string value);
    partial void OnAddUserChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    partial void OnUpdateUserChanging(string value);
    partial void OnUpdateUserChanged();
    partial void OnOtherAccountTypeChanging(string value);
    partial void OnOtherAccountTypeChanged();
    partial void OnOtherUserNameChanging(string value);
    partial void OnOtherUserNameChanged();
    partial void OnOtherPassWordChanging(string value);
    partial void OnOtherPassWordChanged();
    partial void OnIsGuestManagerChanging(System.Nullable<bool> value);
    partial void OnIsGuestManagerChanged();
    partial void OnYouMianBiLiChanging(System.Nullable<int> value);
    partial void OnYouMianBiLiChanged();
    partial void OnZheKouBiLiChanging(System.Nullable<int> value);
    partial void OnZheKouBiLiChanged();
    #endregion
		
		public SysGroupUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL")]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this.OnStoreIDChanging(value);
					this.SendPropertyChanging();
					this._StoreID = value;
					this.SendPropertyChanged("StoreID");
					this.OnStoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrueName", DbType="NVarChar(50)")]
		public string TrueName
		{
			get
			{
				return this._TrueName;
			}
			set
			{
				if ((this._TrueName != value))
				{
					this.OnTrueNameChanging(value);
					this.SendPropertyChanging();
					this._TrueName = value;
					this.SendPropertyChanged("TrueName");
					this.OnTrueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentToken", DbType="VarChar(50)")]
		public string CurrentToken
		{
			get
			{
				return this._CurrentToken;
			}
			set
			{
				if ((this._CurrentToken != value))
				{
					this.OnCurrentTokenChanging(value);
					this.SendPropertyChanging();
					this._CurrentToken = value;
					this.SendPropertyChanged("CurrentToken");
					this.OnCurrentTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllStore", DbType="Bit")]
		public System.Nullable<bool> AllStore
		{
			get
			{
				return this._AllStore;
			}
			set
			{
				if ((this._AllStore != value))
				{
					this.OnAllStoreChanging(value);
					this.SendPropertyChanging();
					this._AllStore = value;
					this.SendPropertyChanged("AllStore");
					this.OnAllStoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreList", DbType="VarChar(8000)")]
		public string StoreList
		{
			get
			{
				return this._StoreList;
			}
			set
			{
				if ((this._StoreList != value))
				{
					this.OnStoreListChanging(value);
					this.SendPropertyChanging();
					this._StoreList = value;
					this.SendPropertyChanged("StoreList");
					this.OnStoreListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACBind", DbType="VarChar(50)")]
		public string MACBind
		{
			get
			{
				return this._MACBind;
			}
			set
			{
				if ((this._MACBind != value))
				{
					this.OnMACBindChanging(value);
					this.SendPropertyChanging();
					this._MACBind = value;
					this.SendPropertyChanged("MACBind");
					this.OnMACBindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="VarChar(50)")]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WXID", DbType="VarChar(100)")]
		public string WXID
		{
			get
			{
				return this._WXID;
			}
			set
			{
				if ((this._WXID != value))
				{
					this.OnWXIDChanging(value);
					this.SendPropertyChanging();
					this._WXID = value;
					this.SendPropertyChanged("WXID");
					this.OnWXIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShouQuanCode", DbType="VarChar(50)")]
		public string ShouQuanCode
		{
			get
			{
				return this._ShouQuanCode;
			}
			set
			{
				if ((this._ShouQuanCode != value))
				{
					this.OnShouQuanCodeChanging(value);
					this.SendPropertyChanging();
					this._ShouQuanCode = value;
					this.SendPropertyChanged("ShouQuanCode");
					this.OnShouQuanCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckCode", DbType="Int")]
		public System.Nullable<int> CheckCode
		{
			get
			{
				return this._CheckCode;
			}
			set
			{
				if ((this._CheckCode != value))
				{
					this.OnCheckCodeChanging(value);
					this.SendPropertyChanging();
					this._CheckCode = value;
					this.SendPropertyChanged("CheckCode");
					this.OnCheckCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckTime
		{
			get
			{
				return this._LastCheckTime;
			}
			set
			{
				if ((this._LastCheckTime != value))
				{
					this.OnLastCheckTimeChanging(value);
					this.SendPropertyChanging();
					this._LastCheckTime = value;
					this.SendPropertyChanged("LastCheckTime");
					this.OnLastCheckTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManager", DbType="Bit")]
		public System.Nullable<bool> IsManager
		{
			get
			{
				return this._IsManager;
			}
			set
			{
				if ((this._IsManager != value))
				{
					this.OnIsManagerChanging(value);
					this.SendPropertyChanging();
					this._IsManager = value;
					this.SendPropertyChanged("IsManager");
					this.OnIsManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnable", DbType="Bit")]
		public System.Nullable<bool> IsEnable
		{
			get
			{
				return this._IsEnable;
			}
			set
			{
				if ((this._IsEnable != value))
				{
					this.OnIsEnableChanging(value);
					this.SendPropertyChanging();
					this._IsEnable = value;
					this.SendPropertyChanged("IsEnable");
					this.OnIsEnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YouMian", DbType="Money")]
		public System.Nullable<decimal> YouMian
		{
			get
			{
				return this._YouMian;
			}
			set
			{
				if ((this._YouMian != value))
				{
					this.OnYouMianChanging(value);
					this.SendPropertyChanging();
					this._YouMian = value;
					this.SendPropertyChanged("YouMian");
					this.OnYouMianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordBak", DbType="VarChar(50)")]
		public string PasswordBak
		{
			get
			{
				return this._PasswordBak;
			}
			set
			{
				if ((this._PasswordBak != value))
				{
					this.OnPasswordBakChanging(value);
					this.SendPropertyChanging();
					this._PasswordBak = value;
					this.SendPropertyChanged("PasswordBak");
					this.OnPasswordBakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this.OnAddTimeChanging(value);
					this.SendPropertyChanging();
					this._AddTime = value;
					this.SendPropertyChanged("AddTime");
					this.OnAddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddUser", DbType="VarChar(40)")]
		public string AddUser
		{
			get
			{
				return this._AddUser;
			}
			set
			{
				if ((this._AddUser != value))
				{
					this.OnAddUserChanging(value);
					this.SendPropertyChanging();
					this._AddUser = value;
					this.SendPropertyChanged("AddUser");
					this.OnAddUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="VarChar(40)")]
		public string UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherAccountType", DbType="VarChar(50)")]
		public string OtherAccountType
		{
			get
			{
				return this._OtherAccountType;
			}
			set
			{
				if ((this._OtherAccountType != value))
				{
					this.OnOtherAccountTypeChanging(value);
					this.SendPropertyChanging();
					this._OtherAccountType = value;
					this.SendPropertyChanged("OtherAccountType");
					this.OnOtherAccountTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherUserName", DbType="VarChar(50)")]
		public string OtherUserName
		{
			get
			{
				return this._OtherUserName;
			}
			set
			{
				if ((this._OtherUserName != value))
				{
					this.OnOtherUserNameChanging(value);
					this.SendPropertyChanging();
					this._OtherUserName = value;
					this.SendPropertyChanged("OtherUserName");
					this.OnOtherUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherPassWord", DbType="VarChar(1024)")]
		public string OtherPassWord
		{
			get
			{
				return this._OtherPassWord;
			}
			set
			{
				if ((this._OtherPassWord != value))
				{
					this.OnOtherPassWordChanging(value);
					this.SendPropertyChanging();
					this._OtherPassWord = value;
					this.SendPropertyChanged("OtherPassWord");
					this.OnOtherPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGuestManager", DbType="Bit")]
		public System.Nullable<bool> IsGuestManager
		{
			get
			{
				return this._IsGuestManager;
			}
			set
			{
				if ((this._IsGuestManager != value))
				{
					this.OnIsGuestManagerChanging(value);
					this.SendPropertyChanging();
					this._IsGuestManager = value;
					this.SendPropertyChanged("IsGuestManager");
					this.OnIsGuestManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YouMianBiLi", DbType="Int")]
		public System.Nullable<int> YouMianBiLi
		{
			get
			{
				return this._YouMianBiLi;
			}
			set
			{
				if ((this._YouMianBiLi != value))
				{
					this.OnYouMianBiLiChanging(value);
					this.SendPropertyChanging();
					this._YouMianBiLi = value;
					this.SendPropertyChanged("YouMianBiLi");
					this.OnYouMianBiLiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZheKouBiLi", DbType="Int")]
		public System.Nullable<int> ZheKouBiLi
		{
			get
			{
				return this._ZheKouBiLi;
			}
			set
			{
				if ((this._ZheKouBiLi != value))
				{
					this.OnZheKouBiLiChanging(value);
					this.SendPropertyChanging();
					this._ZheKouBiLi = value;
					this.SendPropertyChanged("ZheKouBiLi");
					this.OnZheKouBiLiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaseUserRight")]
	public partial class BaseUserRight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UID;
		
		private int _StoreID;
		
		private int _RightID;
		
		private string _UserID;
		
		private bool _IsAllow;
		
		private System.DateTime _AddTime;
		
		private string _AddUser;
		
		private System.DateTime _UpdateTime;
		
		private string _UpdateUser;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUIDChanging(string value);
    partial void OnUIDChanged();
    partial void OnStoreIDChanging(int value);
    partial void OnStoreIDChanged();
    partial void OnRightIDChanging(int value);
    partial void OnRightIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnIsAllowChanging(bool value);
    partial void OnIsAllowChanged();
    partial void OnAddTimeChanging(System.DateTime value);
    partial void OnAddTimeChanged();
    partial void OnAddUserChanging(string value);
    partial void OnAddUserChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnUpdateUserChanging(string value);
    partial void OnUpdateUserChanged();
    #endregion
		
		public BaseUserRight()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this.OnStoreIDChanging(value);
					this.SendPropertyChanging();
					this._StoreID = value;
					this.SendPropertyChanged("StoreID");
					this.OnStoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightID", DbType="Int NOT NULL")]
		public int RightID
		{
			get
			{
				return this._RightID;
			}
			set
			{
				if ((this._RightID != value))
				{
					this.OnRightIDChanging(value);
					this.SendPropertyChanging();
					this._RightID = value;
					this.SendPropertyChanged("RightID");
					this.OnRightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAllow", DbType="Bit NOT NULL")]
		public bool IsAllow
		{
			get
			{
				return this._IsAllow;
			}
			set
			{
				if ((this._IsAllow != value))
				{
					this.OnIsAllowChanging(value);
					this.SendPropertyChanging();
					this._IsAllow = value;
					this.SendPropertyChanged("IsAllow");
					this.OnIsAllowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this.OnAddTimeChanging(value);
					this.SendPropertyChanging();
					this._AddTime = value;
					this.SendPropertyChanged("AddTime");
					this.OnAddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddUser", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string AddUser
		{
			get
			{
				return this._AddUser;
			}
			set
			{
				if ((this._AddUser != value))
				{
					this.OnAddUserChanging(value);
					this.SendPropertyChanging();
					this._AddUser = value;
					this.SendPropertyChanged("AddUser");
					this.OnAddUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaseSystemConfig")]
	public partial class BaseSystemConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SystemConfigID;
		
		private int _StoreID;
		
		private string _SystemConfigName;
		
		private string _SystemConfigAlias;
		
		private string _SystemConfigValue;
		
		private string _AddUser;
		
		private System.DateTime _AddTime;
		
		private string _UpdateUser;
		
		private System.DateTime _UpdateTime;
		
		private string _Memo;
		
		private string _SystemConfigTypeName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystemConfigIDChanging(int value);
    partial void OnSystemConfigIDChanged();
    partial void OnStoreIDChanging(int value);
    partial void OnStoreIDChanged();
    partial void OnSystemConfigNameChanging(string value);
    partial void OnSystemConfigNameChanged();
    partial void OnSystemConfigAliasChanging(string value);
    partial void OnSystemConfigAliasChanged();
    partial void OnSystemConfigValueChanging(string value);
    partial void OnSystemConfigValueChanged();
    partial void OnAddUserChanging(string value);
    partial void OnAddUserChanged();
    partial void OnAddTimeChanging(System.DateTime value);
    partial void OnAddTimeChanged();
    partial void OnUpdateUserChanging(string value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnSystemConfigTypeNameChanging(string value);
    partial void OnSystemConfigTypeNameChanged();
    #endregion
		
		public BaseSystemConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SystemConfigID
		{
			get
			{
				return this._SystemConfigID;
			}
			set
			{
				if ((this._SystemConfigID != value))
				{
					this.OnSystemConfigIDChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigID = value;
					this.SendPropertyChanged("SystemConfigID");
					this.OnSystemConfigIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this.OnStoreIDChanging(value);
					this.SendPropertyChanging();
					this._StoreID = value;
					this.SendPropertyChanged("StoreID");
					this.OnStoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemConfigName
		{
			get
			{
				return this._SystemConfigName;
			}
			set
			{
				if ((this._SystemConfigName != value))
				{
					this.OnSystemConfigNameChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigName = value;
					this.SendPropertyChanged("SystemConfigName");
					this.OnSystemConfigNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigAlias", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemConfigAlias
		{
			get
			{
				return this._SystemConfigAlias;
			}
			set
			{
				if ((this._SystemConfigAlias != value))
				{
					this.OnSystemConfigAliasChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigAlias = value;
					this.SendPropertyChanged("SystemConfigAlias");
					this.OnSystemConfigAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigValue", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string SystemConfigValue
		{
			get
			{
				return this._SystemConfigValue;
			}
			set
			{
				if ((this._SystemConfigValue != value))
				{
					this.OnSystemConfigValueChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigValue = value;
					this.SendPropertyChanged("SystemConfigValue");
					this.OnSystemConfigValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddUser", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AddUser
		{
			get
			{
				return this._AddUser;
			}
			set
			{
				if ((this._AddUser != value))
				{
					this.OnAddUserChanging(value);
					this.SendPropertyChanging();
					this._AddUser = value;
					this.SendPropertyChanged("AddUser");
					this.OnAddUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this.OnAddTimeChanging(value);
					this.SendPropertyChanging();
					this._AddTime = value;
					this.SendPropertyChanged("AddTime");
					this.OnAddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemConfigTypeName
		{
			get
			{
				return this._SystemConfigTypeName;
			}
			set
			{
				if ((this._SystemConfigTypeName != value))
				{
					this.OnSystemConfigTypeNameChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigTypeName = value;
					this.SendPropertyChanged("SystemConfigTypeName");
					this.OnSystemConfigTypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaseSystemConfigDefault")]
	public partial class BaseSystemConfigDefault : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SystemConfigID;
		
		private string _SystemConfigName;
		
		private string _SystemConfigAlias;
		
		private string _SystemConfigValue;
		
		private string _AddUser;
		
		private System.DateTime _AddTime;
		
		private string _UpdateUser;
		
		private System.DateTime _UpdateTime;
		
		private string _Memo;
		
		private int _Type;
		
		private string _SystemConfigTypeName;
		
		private bool _IsVisible;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystemConfigIDChanging(int value);
    partial void OnSystemConfigIDChanged();
    partial void OnSystemConfigNameChanging(string value);
    partial void OnSystemConfigNameChanged();
    partial void OnSystemConfigAliasChanging(string value);
    partial void OnSystemConfigAliasChanged();
    partial void OnSystemConfigValueChanging(string value);
    partial void OnSystemConfigValueChanged();
    partial void OnAddUserChanging(string value);
    partial void OnAddUserChanged();
    partial void OnAddTimeChanging(System.DateTime value);
    partial void OnAddTimeChanged();
    partial void OnUpdateUserChanging(string value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnSystemConfigTypeNameChanging(string value);
    partial void OnSystemConfigTypeNameChanged();
    partial void OnIsVisibleChanging(bool value);
    partial void OnIsVisibleChanged();
    #endregion
		
		public BaseSystemConfigDefault()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SystemConfigID
		{
			get
			{
				return this._SystemConfigID;
			}
			set
			{
				if ((this._SystemConfigID != value))
				{
					this.OnSystemConfigIDChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigID = value;
					this.SendPropertyChanged("SystemConfigID");
					this.OnSystemConfigIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemConfigName
		{
			get
			{
				return this._SystemConfigName;
			}
			set
			{
				if ((this._SystemConfigName != value))
				{
					this.OnSystemConfigNameChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigName = value;
					this.SendPropertyChanged("SystemConfigName");
					this.OnSystemConfigNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigAlias", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemConfigAlias
		{
			get
			{
				return this._SystemConfigAlias;
			}
			set
			{
				if ((this._SystemConfigAlias != value))
				{
					this.OnSystemConfigAliasChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigAlias = value;
					this.SendPropertyChanged("SystemConfigAlias");
					this.OnSystemConfigAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigValue", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string SystemConfigValue
		{
			get
			{
				return this._SystemConfigValue;
			}
			set
			{
				if ((this._SystemConfigValue != value))
				{
					this.OnSystemConfigValueChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigValue = value;
					this.SendPropertyChanged("SystemConfigValue");
					this.OnSystemConfigValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddUser", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AddUser
		{
			get
			{
				return this._AddUser;
			}
			set
			{
				if ((this._AddUser != value))
				{
					this.OnAddUserChanging(value);
					this.SendPropertyChanging();
					this._AddUser = value;
					this.SendPropertyChanged("AddUser");
					this.OnAddUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this.OnAddTimeChanging(value);
					this.SendPropertyChanging();
					this._AddTime = value;
					this.SendPropertyChanged("AddTime");
					this.OnAddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemConfigTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemConfigTypeName
		{
			get
			{
				return this._SystemConfigTypeName;
			}
			set
			{
				if ((this._SystemConfigTypeName != value))
				{
					this.OnSystemConfigTypeNameChanging(value);
					this.SendPropertyChanging();
					this._SystemConfigTypeName = value;
					this.SendPropertyChanged("SystemConfigTypeName");
					this.OnSystemConfigTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit NOT NULL")]
		public bool IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this.OnIsVisibleChanging(value);
					this.SendPropertyChanging();
					this._IsVisible = value;
					this.SendPropertyChanged("IsVisible");
					this.OnIsVisibleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
